repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=5000
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: (README\.md)$
      - id: fix-byte-order-marker
      - id: forbid-new-submodules # I hate submodules
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: pretty-format-json
        args:
          - --autofix
        exclude: (.vscode\/.+)$
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  # Dockerfile Linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint

  # Bash Linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args:
          - --exclude=SC1091 # shellcheck-py has trouble following sourced files for some reason, even with source= specified

  # Fixing text problems
  - repo: https://github.com/sirosen/texthooks
    rev: 0.4.0
    hooks:
      - id: fix-smartquotes
      - id: fix-ligatures
      - id: forbid-bidi-controls

  # Markdown Linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint-fix-docker
