version: '3.4'
services:
  nginx:
    image: makeshift27015/nginx-alpine-amplify
    ports:
      - "80:80"
    environment:
      - API_KEY=${API_KEY} # Replace with yours
      - AMPLIFY_IMAGENAME=${AMPLIFY_IMAGENAME} # Replace with yours
